const ConstUtils = {
  ACTION: {
    SET_FILTER_BY_TYPE: 'SET_FILTER_BY_TYPE',
    SET_MODEL: 'SET_MODEL',
    SET_ALL: 'SET_ALL',
    TOP_CLOTHES: 'TOP_CLOTHES',
    BOTTOM_CLOTHES: 'BOTTOM_CLOTHES',
    SHOES: 'SHOES',
    HANDBAGS: 'HANDBAGS',
    NECKLACES: 'NECKLACES'
  }
}

export default ConstUtils;